version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["__APP__"]

[main.smtp]
name.en = "SMTP configuration"
name.fr = "Paramètres SMTP"

[main.smtp.from_email]
ask.en = "The email address Baserow will send emails from."
ask.fr = "Adresse d'envoi des messages"
type = "email"
bind = "null"

[main.smtp.smtp_user]
ask.en = "The SMTP user email/id"
ask.fr = "Courriel / id d'utilisateur SMTP"
type = "string"
bind = "SMTP_USER:__INSTALL_DIR__/.env"

[main.smtp.smtp_password]
ask.en = "user password or application token"
ask.fr = "Mot de passe ou jeton d’application SMTP."
type = "password"
bind = "SMTP_PASSWORD:__INSTALL_DIR__/.env"

[main.smtp.smtp_host]
ask.en = "SMTP host"
ask.fr = "Nom d’hôte du serveur SMTP"
type = "string"
bind = "SMTP_HOST:__INSTALL_DIR__/.env"

[main.smtp.smtp_port]
ask.en = "SMTP port"
ask.fr = "Port du serveur SMTP"
type = "number"
optional = true
bind = "SMTP_PORT:__INSTALL_DIR__/.env"

[main.instance.registration]
    type = "boolean"
    ask.en = "Allow registration?"
    ask.fr = "Autoriser les inscriptions?"
    default = true
    bind = "AUTH_IS_REGISTRATION_ENABLED:__INSTALL_DIR__/.env"

[main.instance.password_reset]
    type = "boolean"
    ask.en = "Allow password reset?"
    ask.fr = "Autoriser le changement de mot de passe?"
    default = true
    bind = "AUTH_IS_PASSWORD_RESET_ENABLED:__INSTALL_DIR__/.env"

[main.instance.email_verification]
    type = "boolean"
    ask.en = "Whether email verification is required"
    ask.fr = "Vérification obligatoire de l'adresse de courriel"
    default = true
    bind = "AUTH_IS_EMAIL_VERIFICATION_REQUIRED:__INSTALL_DIR__/.env"
    
[main.instance.retention]
    type = "number"
    ask.en = "The retention period in days for deleted documents."
    ask.fr = "Durée de rétention des documents en jours"
    default = 30
    bind = "DOCUMENTS_DELETED_DOCUMENTS_RETENTION_DAYS:__INSTALL_DIR__/.env"

#[main.ai]
#name.en = "AI models"
#name.fr = "Modèles AI"

#[main.ai.baserow_ollama_host]
#ask.en = "Server address"
#ask.fr = "Adresse du serveur"
#type = "url"
#bind = "BASEROW_OLLAMA_HOST:__INSTALL_DIR__/__APP__/.env"

#[main.ai.baserow_ollama_models]
#ask.en = "List of models"
#ask.fr = "Liste des modèles"
#help.en = "List of available models, separated by commas"
#help.fr = "Liste des modèles disponibles, séparés par des virgules"
#type = "string"
#bind = "BASEROW_OLLAMA_MODELS:__INSTALL_DIR__/__APP__/.env"

[main.limit_size]
name.en = "Upload limit size"
name.fr = "Téléchargement de fichiers"

[main.limit_size.warning]
ask.fr = "Taille limite pour l'import de fichiers dans Baserow (paramètre reporté dans la configuration NGINX du domaine)."
ask.en = "Baserow size limit file upload"
type = "alert"
style = "info"

[main.limit_size.upload_max_size]
ask.fr = "Taille limite pour le téléchargement des fichiers en Mo"
ask.en = "Size limit file upload (Mb)"
type = "number"
bind = "null"



# [main.storage]
# name.en = "AWS S3 bucket"
# name.fr = "AWS S3 bucket"

# [main.storage.access_key_id]
# ask = "AWS_ACCESS_KEY_ID"
# type = "string"
# bind = "AWS_ACCESS_KEY_ID:__INSTALL_DIR__/__APP__/.env"

# [main.storage.secret_access_key]
# ask = "AWS_SECRET_ACCESS_KEY"
# type = "password"
# bind = "AWS_SECRET_ACCESS_KEY:__INSTALL_DIR__/__APP__/.env"

# [main.storage.AWS_STORAGE_BUCKET_NAME]
# ask = "AWS_STORAGE_BUCKET_NAME"
# type = "string"
# bind = "AWS_STORAGE_BUCKET_NAME:__INSTALL_DIR__/__APP__/.env"

# [main.storage.AWS_S3_REGION_NAME]
# ask = "AWS_S3_REGION_NAME"
# type = "string"
# bind = "AWS_S3_REGION_NAME:__INSTALL_DIR__/__APP__/.env"

# [main.storage.AWS_S3_ENDPOINT_URL]
# ask = "AWS_S3_ENDPOINT_URL"
# type = "url"
# bind = "AWS_S3_ENDPOINT_URL:__INSTALL_DIR__/__APP__/.env"

# [main.storage.AWS_S3_CUSTOM_DOMAIN]
# ask = "AWS_S3_CUSTOM_DOMAIN"
# type = "url"
# bind = "AWS_S3_CUSTOM_DOMAIN:__INSTALL_DIR__/__APP__/.env"
