version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["__APP__"]

[main.smtp]
name.en = "SMTP configuration"
name.fr = "Paramètres SMTP"

[main.smtp.from_email]
ask.en = "The email address Baserow will send emails from."
ask.fr = "Adresse d'envoi des messages"
type = "email"
bind = "null"

[main.smtp.smtp_user]
ask.en = "The SMTP user email/id"
ask.fr = "Courriel / id d'utilisateur SMTP"
type = "string"
bind = "SMTP_USER:__INSTALL_DIR__/.env"

[main.smtp.smtp_password]
ask.en = "user password or application token"
ask.fr = "Mot de passe ou jeton d’application SMTP."
type = "password"
bind = "SMTP_PASSWORD:__INSTALL_DIR__/.env"

[main.smtp.smtp_host]
ask.en = "SMTP host"
ask.fr = "Nom d’hôte du serveur SMTP"
type = "string"
bind = "SMTP_HOST:__INSTALL_DIR__/.env"

[main.smtp.smtp_port]
ask.en = "SMTP port"
ask.fr = "Port du serveur SMTP"
type = "number"
optional = true
bind = "SMTP_PORT:__INSTALL_DIR__/.env"

[main.instance]
[main.instance.registration]
    type = "boolean"
    ask.en = "Allow registration?"
    ask.fr = "Autoriser les inscriptions?"
    default = true
    bind = "AUTH_IS_REGISTRATION_ENABLED:__INSTALL_DIR__/.env"

[main.instance.password_reset]
    type = "boolean"
    ask.en = "Allow password reset?"
    ask.fr = "Autoriser le changement de mot de passe?"
    default = true
    bind = "AUTH_IS_PASSWORD_RESET_ENABLED:__INSTALL_DIR__/.env"

[main.instance.email_verification]
    type = "boolean"
    ask.en = "Whether email verification is required"
    ask.fr = "Vérification obligatoire de l'adresse de courriel"
    default = true
    bind = "AUTH_IS_EMAIL_VERIFICATION_REQUIRED:__INSTALL_DIR__/.env"
    
[main.instance.retention]
    type = "number"
    ask.en = "The retention period in days for deleted documents."
    ask.fr = "Durée de rétention des documents en jours"
    default = 30
    bind = "DOCUMENTS_DELETED_DOCUMENTS_RETENTION_DAYS:__INSTALL_DIR__/.env"

[main.storage]

    [main.storage.doc_storage_driver]
    ask.en = "Storage driver"
    ask.fr = "Storage driver"
    type = "select"
    choices = ["filesystem", "s3", "in-memory", "azure-blob"]

    [main.storage.aws_endpoint]
    ask.en = "S3 endpoint"
    ask.fr = "S3 endpoint"
    bind = "DOCUMENT_STORAGE_S3_ENDPOINT:__INSTALL_DIR__/.env"
    
    [main.storage.aws_bucket_name]
    ask.en = "Bucket name"
    ask.fr = "Nom du bucket"
    bind = "DOCUMENT_STORAGE_S3_BUCKET_NAME:__INSTALL_DIR__/.env"

    [main.storage.aws_key_id]
    ask.en = "S3 key id"
    ask.fr = "S3 key id"
    bind = "DOCUMENT_STORAGE_S3_ACCESS_KEY_ID:__INSTALL_DIR__/.env"

    [main.storage.aws_secret_key]
    ask.en = "S3 secret key"
    ask.fr = "S3 secret key"
    bind = "DOCUMENT_STORAGE_S3_SECRET_ACCESS_KEY:__INSTALL_DIR__/.env"

[main.uploads]
name.en = "Upload limit size"
name.fr = "Téléchargement de fichiers"

[main.uploads.warning]
ask.fr = "Taille limite pour l'import de fichiers (paramètre reporté dans la configuration NGINX du domaine)."
ask.en = "Baserow size limit file upload"
type = "alert"
style = "info"

[main.uploads.max_upload_size]
ask.fr = "Taille limite pour le téléchargement des fichiers en Mo"
ask.en = "Size limit file upload (Mb)"
type = "number"
bind = "null"



"
